# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  dbserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "VerySecurePassw0rd!"
      MSSQL_PID: Express
    ports:
      - "11433:1433"
  dotnetapidemo:
    image: dotnetapidemo
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      DbServer: "dbserver"
      DbPort: "1433"
      DbUser: "SA"
      Password: "VerySecurePassw0rd!"
      Database: "DotnetApiDemo"
    ports:
      - 8001:80
    depends_on: 
      - dbserver
